/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_solidark_projcanvas_MainActivity */

#ifndef _Included_com_solidark_projcanvas_MainActivity
#define _Included_com_solidark_projcanvas_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_solidark_projcanvas_MainActivity
 * Method:    ocvFrame
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_solidark_projcanvas_MainActivity_ocvFrame
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_solidark_projcanvas_MainActivity
 * Method:    ocvRecalibrate
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_solidark_projcanvas_MainActivity_ocvRecalibrate
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
